proxies:
  - name: Japan-Xray
    type: vless
    server: 101.36.104.80
    port: 443
    uuid: 556db051-84a5-4a25-877f-4fb365d325ec
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: www.cloudflare.com
    reality-opts:
      public-key: wvZMisOu5dUS4F1roc6iFOCpe-yGX7pfAikYLdBVtB4
      short-id: 52663672a2781cad
    client-fingerprint: chrome

proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - Japan-Xray
      - DIRECT

rules:
  - GEOIP,CN,DIRECT
  - MATCH,🚀 节点选择
